### ISSUE TITLE
cannot be install as plugin in wordpress...

### ISSUE THREAD

**Issue by mxmkmarquette** [o10n-x/wordpress-o10n-core#1]
it's telling me that 

Installing Plugin from uploaded file: |%r5h.zip
Unpacking the package…

Installing the plugin…

The package could not be installed. No valid plugins were found.

Plugin installation failed.

Return to Plugin Installer

**Comment by optimalisatie** [comment]
Hi Maxime,

Thank you very much for your feedback!

This Github repository is not a plugin. It is for development purposes only and was created after a suggestion by Viktor Szépe (author of https://github.com/szepeviktor/w3-total-cache-fixed). This repository will be linked to the optimization plugin repositories as a Github module.

https://github.com/o10n-x/wordpress-cloudfront-page-cache/issues/2

We have added a warning to the description:

> **This is not a WordPress plugin! This repository is for development purposes only.**
